### ISSUE TITLE
Logical Interaction Suppor

### ISSUE THREAD

**Issue by OlegDokuka** [ReactiveSocket/reactivesocket-tck#41]
After a successful connection establishment requester should be able to request 

- [ ] FireAndForget (Success)
- [ ] MetadataPush (Success)
- [ ] RequestResponse (Success | Failure)
- [ ] RequestStream (Success | Failure)
- [ ] RequestChannel (Success | Failure)
