### ISSUE TITLE
Successful Connection Establishment

### ISSUE THREAD

**Issue by alex-dukhno** [ReactiveSocket/reactivesocket-tck#51]
- [x] Successfull Connection Establishment (#50)
- [ ] Successfull Connection Establishment with RESUME flag enabled (that means that server supports resumability)
- [ ] Successfull Connection Establishment with LEASE flag enabled (that means that server supports leasing)
