### ISSUE TITLE
Testing Server Connection Establishment

### ISSUE THREAD

**Issue by alex-dukhno** [ReactiveSocket/reactivesocket-tck#52]
- [ ] Failure Connection Establishment
   - [ ] malformed frame (random bytes)
       - [ ] stream is not 0
       - [ ] keepalive is <= 0
       - [ ] max-life-time is <= 0
       - [ ] frame does contain all required fields
   - [ ] valid frame before SETUP frame
INVALID_SETUP - if version is not supported
UNSUPPORTED_SETUP - if frame is malformed
- [ ] Failure Connection Establishment with RESUME flag enabled
    - [ ] SETUP frame but server doesn't support resumability
    - [ ] RESUME frame but server doesn't support resumability
    - [ ] RESUME frame but session has expired
    - [ ] malformed SETUP with RESUME flag (e.g. no resume token) or without RESUME flag with resume token
Server sends REJECTED_RESUME
- [ ] Failure Connection Establishment with LEASE flag enabled
    - [ ] Server without support leasing
